version: '3.8'

services:
  db:
    image: mysql:latest
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      retries: 5
      start_period: 10s

  discord-bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "${DISCORD_PORT}:5000"

volumes:
  mysqldata:
