version: '3.8'

services:
  db:
    image: mysql:latest
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  discord-bot:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "${DISCORD_PORT}:5000"

volumes:
  mysqldata:
